package com.nubix.market.config;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Componente que se ejecuta al inicializar la aplicación para aplicar parches
 * directamente sobre el esquema de la base de datos.
 * Asegura específicamente que la tabla de tokens de recuperación de contraseña 
 * (password_reset_tokens) exista y tenga su identificador configurado como autoincremental.
 */
@Component
public class PasswordResetSchemaPatch {

    private static final Logger log = LoggerFactory.getLogger(PasswordResetSchemaPatch.class);

    private final JdbcTemplate jdbcTemplate;

    /**
     * Constructor para la inyección de dependencias.
     *
     * @param jdbcTemplate Herramienta principal de Spring para ejecutar consultas SQL de forma segura.
     */

    public PasswordResetSchemaPatch(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Método ejecutado automáticamente después de que Spring inicializa este bean (@PostConstruct).
     * Intenta crear la tabla de tokens si no existe y luego ejecuta un comando ALTER TABLE 
     * para garantizar que la columna 'id' sea autogenerada por defecto.
     * Los errores durante este proceso son capturados y registrados en el log para evitar 
     * que la aplicación deje de arrancar.
     */
    @PostConstruct
    public void patch() {
        try {
            jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS password_reset_tokens (
                        id BIGSERIAL PRIMARY KEY,
                        codigo VARCHAR(6) NOT NULL,
                        fecha_expiracion TIMESTAMP(6) NOT NULL,
                        utilizado BOOLEAN NOT NULL DEFAULT FALSE,
                        usuario_id INTEGER NOT NULL,
                        CONSTRAINT fk_reset_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
                    )
                    """);
            try {
                jdbcTemplate.execute(
                        "ALTER TABLE password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
            } catch (Exception ignored) {
                // Ya configurado
            }
            log.debug("Tabla password_reset_tokens verificada");
        } catch (Exception e) {
            log.warn("No se pudo aplicar parche de password_reset_tokens: {}", e.getMessage());
        }
    }
}
