package com.nubix.market.config;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Parche de esquema al arranque que asegura que la tabla de tokens de restablecimiento
 * de contraseña exista y tenga un identificador autoincremental en PostgreSQL/Supabase.
 *
 * @author Grupo de Desarrollo Nubix Market
 * @version 1.0.0 (2026)
 */
@Component
public class PasswordResetSchemaPatch {

    private static final Logger log = LoggerFactory.getLogger(PasswordResetSchemaPatch.class);

    private final JdbcTemplate jdbcTemplate;

    /**
     * Inyecta el template JDBC para ejecutar DDL idempotente al iniciar la aplicación.
     *
     * @param jdbcTemplate acceso JDBC de Spring
     */
    public PasswordResetSchemaPatch(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Crea la tabla {@code password_reset_tokens} si no existe y ajusta la columna
     * {@code id} como identidad generada cuando el motor lo permite.
     */
    @PostConstruct
    public void patch() {
        try {
            jdbcTemplate.execute("""
                    CREATE TABLE IF NOT EXISTS password_reset_tokens (
                        id BIGSERIAL PRIMARY KEY,
                        codigo VARCHAR(6) NOT NULL,
                        fecha_expiracion TIMESTAMP(6) NOT NULL,
                        utilizado BOOLEAN NOT NULL DEFAULT FALSE,
                        usuario_id INTEGER NOT NULL,
                        CONSTRAINT fk_reset_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
                    )
                    """);
            try {
                jdbcTemplate.execute(
                        "ALTER TABLE password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
            } catch (Exception ignored) {
                // Ya configurado
            }
            log.debug("Tabla password_reset_tokens verificada");
        } catch (Exception e) {
            log.warn("No se pudo aplicar parche de password_reset_tokens: {}", e.getMessage());
        }
    }
}
